version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - './app/data:/var/lib/grafana'
      - './app/grafana.ini:/etc/grafana/grafana.ini'
    env_file:
      - .env
    networks:
      - grafana

networks:
  grafana:
